################################################################################
MLI_FILE		= cordova_device.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-device
################################################################################
